language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install ."
script:
  - "fusesoc init -y"
  - "fusesoc list-systems"
  - "fusesoc list-cores"
  - "fusesoc update"
  - "py.test"
